apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: local.herbamatte.apps
  namespace: '{{ .Values.argocd.namespace }}'
  annotations:
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
