apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - port: 8000
    targetPort: 80
    name: pihole-admin
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
  - port: 853
    targetPort: 53
    protocol: TCP
    name: secdns-tcp
  - port: 853
    targetPort: 53
    protocol: UDP
    name: secdns-udp
  externalIPs:
  - 10.1.100.63
